name: opensailphotography
favicon: null
layout_spectrum: 0.0851893131621182
typography_spectrum: 0.4464253175538033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2943777779582888
  lightness: 0.19422916881740093
  saturation: 0.2309110681526363
  rhythmicContrast: 0.2166990910191089
purpose: []
